// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puchlceouhehddtyoosj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1Y2hsY2VvdWhlaGRkdHlvb3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTgxODYsImV4cCI6MjA2NjI3NDE4Nn0.W6gV_o1Nw2Bp75sGfvKc1X6WK-EJCuPXL-3QW-CxxYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);